### ISSUE TITLE
Fastlane: Changelogs have wrong names

### ISSUE THREAD

**Issue by IzzySoft** [aldrinzigmundv/digilogtv#2]
You are currently using `<versionName>.txt` for your fastlane changelogs. This should be `<versionCode>.txt` to be recognized (e.g. `6.txt` for version 1.8.0).

**Comment by aldrinzigmundv** [comment]
Thank you for bringing this to my attention. I've made the necessary changes. Sorry, I haven't opened GitLab for awhile. Currently workin on several apps...

**Comment by IzzySoft** [comment]
Thanks! I've just manually pulled in the last one, and adjusted the config at my end to pull future changelogs automatically. All the best for your "parallel workload" :smiley:

Btw, you might wish to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to accompany the lonely PlayStore one in your Readme, and link it to `https://apt.izzysoft.de/packages/io.github.aldrinzigmundv.digilogtv/` :wink:
