### ISSUE TITLE
Can't scroll channel list on Android tv box

### ISSUE THREAD

**Issue by mfat** [aldrinzigmundv/digilogtv#3]
I can't scroll the channel list either with the up down keys or drag and drop with mouse. Thanks.

**Comment by aldrinzigmundv** [comment]
I haven't tried the app on Android TV yet. Also, Flutter, which is what I used on  this app, although created by Google, doesn't have official support for Android TV yet. I've read that most apps will only require minor adjustments to work well with Android TV though. I'll start looking into it when I have the time. In the meantime, screen mirroring could serve as an alternative solution.

**Comment by aldrinzigmundv** [comment]
The latest version, 2.0.0, featuring compatibility for Google and Android TV, has been uploaded and is now available in the releases section of this GitHub repository. However, please note that it is still awaiting approval on Google Play, a process that typically takes 24-72 hours. Kindly check it out and inform me if you encounter any issues. Thank you.
