### ISSUE TITLE
"Contact me" tab says I've downloaded from Play Store while I downloaded from GitHub

### ISSUE THREAD

**Issue by mfat** [aldrinzigmundv/digilogtv#4]
Title

**Comment by aldrinzigmundv** [comment]
Looks like I forgot to get the app to display a different message when it's not downloaded from the Google Play Store. You shouldn't receive ads from the app itself though, if you didn't download it from Google Play. I'll get this issue fixed. Thank you for bringing it to my attention.

**Comment by aldrinzigmundv** [comment]
I have fixed the issue, and new channels have just been added as well. Thank you.
