### ISSUE TITLE
app not showing in app section (android tv)

### ISSUE THREAD

**Issue by FrankyHolly** [aldrinzigmundv/digilogtv#5]
Hi, great work thank you for this app!!
The app is not showing in the main app section of android tv, the workaround being 'settings---apps---all apps' where it does show and is launcheable. It is possible to have 'sideloaded' apps shown in the main apps section (eg droid-fy, aurora store).

**Comment by aldrinzigmundv** [comment]
I actually don't have a TV and was only aware of the navigation issues. I tried checking the official docs and found that I'm still missing a few requirements, including a banner for TV launchers. I just fixed that right now. The new release with the fixes is already in the [Releases Section](https://github.com/aldrinzigmundv/digilogtv/releases/latest). Thank you for reporting the issue, and please keep reaching out if you find any more.
